### ISSUE TITLE
"Enable multithreading to use std::thread: Operation not permitted" error

### ISSUE THREAD

**Issue by erifa1** [mreppell/Karp#1]
Hi, 

I had this issue by using the example datas: 

```
user1@comp1[example] sudo karp -c quantify -r reference.fasta -i reference.index -f simulated.data.fastq.gz -o simulated.results -t reference.tax
Reading fasta index
Calculating likelihood based read filter parameters
Likelihood filter parameters: mean=-1.85842 SD=2.93197
Kmer length: 31
Number of targets: 500
Number of kmers: 449,511
Number of equivalence classes: 10,559
Running in single-end mode
Process file 1: simulated.data.fastq.gz
Finding pseudoalignments for the reads ...terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
```

I modified this file:  **~/Karp/build/src/CMakeFiles/karp.dir/link.txt**, `-lpthread` appears two times, and it needs this option `-Wl,--no-as-needed`

This version works for me: 
`/usr/bin/c++       CMakeFiles/karp.dir/new_main.cpp.o  -o karp -rdynamic libkarp_core.a -lhdf5 -lz -ldl -lm -lrt -Wl,--no-as-needed -lpthread`

`make -j #in ~/Karp/build`

And it works well! 
Regards

ubuntu 14.04 LTS
cmake version 2.8.12.2
GNU Make 3.81
c++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by mreppell** [comment]
Thank you for finding this issue. I realize the way I was adding the compile options -Wl,--no-as-needed in my CMakeLists.txt file they were not actually included in the final linking. I have updated the CMakeLists.txt to add these options. I was not able to recreate your issue on my hardware, so I have not been able to test that the fix works, but the options are correctly included now.
